config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  # Defines the root path route ("/")
  # root "articles#index"
  # root to: 'recipes#index'
  resources :users
  resources :recipes do
    resources :recipe_foods
  end
  resources :foods
  resources :public_recipes, only: [:index]
  resources :generate, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    return unless user_signed_in?

    return unless current_user && user

    can :read, :all
    can :destroy, Food, user: current_user
    can :destroy, Recipe, user: current_user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  # Determine where to redirect user after successful login.
  def after_sign_in_path_for(_resource)
    foods_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @new_food = Food.new
  end

  def create
    food = Food.new(user: current_user, **post_params)
    if food.save
      redirect_to foods_path notice: 'Food added successfully'
    else
      render :new
    end
  end

  def destroy
    food = Food.find(params[:id])
    if food.destroy
      flash[:notice] = 'Food deleted'
    else
      flash[:alert] = 'Couldn\'t delete food'
    end
    redirect_to foods_path
  end

  def post_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/generate_controller.rb
class GenerateController < ApplicationController
  def index
    @recipes = Recipe.includes(:recipe_foods).where(user: current_user)
    @amount_of_food = 0
    @recipes.each do |recipe|
      @amount_of_food += recipe.recipe_foods.count
    end

    @total = 0
    @recipes.each do |recipe|
      recipe.recipe_foods.each do |recipe_food|
        @total += recipe_food.food.price * recipe_food.quantity
      end
    end

    @recipe_foods_arr = []
    @recipes.each do |recipe|
      @recipe_foods_arr.concat(recipe.recipe_foods)
    end
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:recipe_foods, :foods).order(created_at: :desc)
    @public_recipes = @recipes.select(&:public)

    @total_price = []
    @public_recipes.each do |recipe|
      total = 0
      recipe.recipe_foods.each do |recipe_food|
        total += recipe_food.food.price * recipe_food.quantity
      end
      @total_price.push(total)
    end
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def show
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe
    return if @recipe.user == current_user

    flash[:alert] = 'Access Denied.'
    redirect_to recipes_path
  end

  def new
    recipe = Recipe.find(params[:recipe_id])
    unless recipe.user == current_user
      flash[:alert] = 'Access Denied.'
      return redirect_to recipes_path
    end
    @recipe_food = RecipeFood.new
    @foods = current_user.foods
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    recipe_food = RecipeFood.new(recipe_food_params)
    recipe_food.recipe = @recipe
    redirect_to recipe_path(@recipe), notice: 'Ingredient added.' if recipe_food.save
  end

  def destroy
    recipe_food = RecipeFood.find(params[:id])
    unless recipe_food.recipe.user == current_user
      flash[:alert] = 'Access Denied.'
      return redirect_to recipes_path
    end
    flash[:notice] = 'Ingredient removed.' if recipe_food.destroy
    redirect_back(fallback_location: root_path)
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe
    unless @recipe.user == current_user
      flash[:alert] = 'Access Denied.'
      return redirect_to recipes_path
    end
    @foods = current_user.foods
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe
    unless @recipe.user == current_user
      flash[:alert] = 'Access Denied.'
      return redirect_to recipes_path
    end
    @recipe_food.update(edit_recipe_food_params)
    flash[:notice] = 'Ingredient updated.'
    redirect_to recipe_path(@recipe)
  end

  def edit_recipe_food_params
    params.require(:edit_recipe_food).permit(:quantity, :food_id)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes
  end

  def show
    recipe_test = Recipe.find(params[:id])
    return redirect_to recipes_path unless recipe_test.user == current_user

    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id).includes(:food, :recipe)
  end

  def destroy
    recipe = Recipe.find(params[:id])
    return flash[:alert] = 'Access Denied.' unless recipe.user == current_user

    flash[:notice] = 'Recipe deleted.' if recipe.destroy
    redirect_back(fallback_location: root_path)
  end

  def create
    recipe = current_user.recipes.new(recipe_params)
    redirect_to recipes_path if recipe.save
  end

  def new
    @recipe = Recipe.new
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.erb
<main>
  <% if user_signed_in? %>
  <div class="action">
    <%= link_to "Add Food", new_food_path, class: "add" %>
    </div>
  <% end %>

  <% if user_signed_in? %>
  <div class="modern-width">
    <table border="">
      <thead>
        <tr>
          <td>Food</td>
          <td>Measurement unit</td>
          <td>Unit Price</td>
          <td>Actions</td>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.measurement_unit %></td>
            <td><%= food.price %></td>
            <td><%= button_to 'Delete', food_path(food), method: :delete ,  class: "remove"%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div>
  <% end %>
</main>

app/views/foods/new.html.erb
<section class="add-items food">
  <h2>Add new Food</h2>

<%= form_with model: @new_food, url: foods_path do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :measurement_unit %><br />
    <%= f.text_field :measurement_unit, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Add Food" , class: "submission" %>
  </div>
<% end %>

</section>

app/views/generate/index.html.erb
<section>
  <h1 class="shopping-header">Shopping List</h1>

  <div class="shopping-totals">
    <p>Amount of food items to buy: <%= @amount_of_food %></p>
    <p>Total value of food needed: $<%= @total %></p>
  </div>
</section>
<section class="shopping-table">
  <table border="|">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe_foods_arr.each do |recipe_food| %>
        <tr>
          <td><%= recipe_food.food.name %></td>
          <td><%= recipe_food.food.measurement_unit %></td>
          <td><%= recipe_food.food.price * recipe_food.quantity %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipeapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
    <header>
      <p>Welcome <%= current_user.name %></p>
      <ul class="nav">
        <li>
          <%= link_to 'Foods |', foods_path %>
        </li>
        <li>
          <%= link_to 'Recipes |', recipes_path %>
        </li>
        <li>
          <%= link_to 'Public recipes', public_recipes_path %>
        </li>
        <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
      </ul>
    </header>
  <% end %>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<div class="public-page">
<h1>Public Recipes</h1>
<ul class="public-recipe">
  <% @public_recipes.each_with_index do |recipe, i| %>
    <li>
      <div>
        <h2>
          <%= link_to recipe.name, recipe_path(recipe) %>
        </h2>
        <p>By: <%= recipe.user.name %></p>
      </div>
      <div>
        <p>Total food items: <%= recipe.recipe_foods.count %></p>
        <p>Total price: <%= @total_price[i] %></p>
      </div>
    </li>
   <% end %>
</ul>
</div>

app/views/recipe_foods/edit.html.erb
<div>
  <%= form_with url: recipe_recipe_food_path, method: :patch, scope: :edit_recipe_food do |form| %>
    <p>Update Ingredient</p>
    <div>
      <%= form.label :quantity, "Quantity", placeholder: 0 %>
      <%= form.number_field :quantity, required: true %>
    </div>
    <div>
      <%= form.label :food_id, "Food" %>
      <div>
        <%= form.collection_select(:food_id, @foods, :id, :name) %>
      </div>
    </div>
    <div>
      <%= form.submit "Update Ingredient" %>
    </div>
  <% end %>
</div>

app/views/recipe_foods/new.html.erb
<div>
  <%= form_with url: recipe_recipe_foods_path, scope: :recipe_food do |form| %>
    <p>Add Ingredient</p>
    <div>
      <%= form.label :quantity, "Quantity", placeholder: 0 %>
      <%= form.number_field :quantity,required: true %>
    </div>
    <div>
      <%= form.label :food_id, "Food" %>
      <div>
        <%= form.collection_select(:food_id, @foods, :id, :name) %>
      </div>
    </div>
    <div>
      <%= form.submit "Add Ingredient" %>
    </div>
  <% end %>
</div>

app/views/recipes/index.html.erb
    <div class="action">
        <%= link_to "Add Recipe", new_recipe_path , class: "add"%>
    </div>
    <div class="modern-width">
    <ul >
      <% @recipes.each do |recipe| %>
        <li class ="recipe-details" >
          <div class="recipe-title">
            <div>
              <%= link_to recipe.name, recipe_path(recipe) %>
            </div>
            <%= button_to "Remove", recipe_path(recipe.id), method: :delete, class: "remove" %>
          </div>
          <div >
            <%= truncate(recipe.description, length: 70) %>
          </div>
        </li>
      <% end %>
    </ul>
    </div>

app/views/recipes/new.html.erb
<div class="add-items recipe">
  <%= form_with model: @recipe , class: "recipe-form" do |form| %>
    <h2>Add a New Recipe</h2>
    <div>
      <%= form.label :name, "Name" %>
      <%= form.text_field :name, placeholder: "Name", required: true, autofocus: true %>
    </div>
    <div>
      <%= form.label :preparation_time, "Preparation Time" %>
      <%= form.number_field :preparation_time, placeholder: 0, required: true, autofocus: true %>
    </div>
    <div>
      <%= form.label :cooking_time, "Cooking Time" %>
      <%= form.number_field :cooking_time, placeholder: 0, required: true, autofocus: true %>
    </div>
    <div>
      <%= form.label :description, "Description" %>
      <%= form.text_area :description, placeholder: "A description of the recipe", rows: 5, required: true, autofocus: true %>
    </div>
    <div>
      <%= form.label :public %><br/>
      <%= form.label :public, "Yes", value: "true" %>
      <%= form.radio_button :public, true, checked: true %>
      <%= form.label :public, "No", value: "false" %>
      <%= form.radio_button :public, false %>
    </div>
    <div>
      <%= form.submit "Add Recipe" , class: "submission" %>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
    <div class="recipe-detailss">
    <p class="recipe-name"><%= @recipe.name+" Recipe" %></p>
      <div class="detail-item">
        <p>Preparation Time: <%= @recipe.preparation_time.to_s + " Hours" %></p>
        <div class="detail-public">
        Public: &nbsp;
        <%if @recipe.public? %>
        <label class="switch">
        <input type="checkbox" checked>
        <span class="slider round"></span>
        </label>
        <%else%>
        <label class="switch">
        <input type="checkbox">
        <span class="slider round"></span>
        </label>
        <%end%>
        </div>
      </div>
      </div>
    <div class="detail-item">
      <p>Cooking Time: <%= @recipe.cooking_time.to_s + " Hours" %></p>
    </div>
    <div class="detail-item">
    <p>Recipe Step:</p>
    <p><%= @recipe.description %></p>
    </div>


    <div class="general-add">
      <% if @recipe.user == current_user %>
        <div class="submissions g-shopping">
          <%= link_to "Generate Shopping List", generate_index_path %>
        </div>
        <div class="submissions g-gredients">
          <%= link_to "Add Ingredient", new_recipe_recipe_food_path(@recipe) %>
        </div>
      <% end %>
    </div>
    <div class="separator"></div>
    <% if @recipe_foods.length >= 0 %>
      <table class="t-border">
        <thead>
          <tr>
            <th>Food</th>
            <th>Quantity</th>
            <th>Value</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @recipe_foods.each do |recipe_food| %>
            <tr>
              <td><%= recipe_food.food.name %></td>
              <td><%= recipe_food.quantity %></td>
              <td>$<%= recipe_food.quantity * recipe_food.food.price %></td>
              <td>
                <% if current_user == recipe_food.recipe.user %>
                 <div class="row">
                  <%= button_to 'Modify', edit_recipe_recipe_food_path(@recipe, recipe_food), method: :get %>
                  <%= button_to 'Remove', recipe_recipe_food_path(@recipe, recipe_food), method: :delete %>
                </div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>